export const fallbackContent = {
  seoTitle: 'Ceylon Horizon | A Peaceful Villa Escape in Sri Lanka',
  seoDescription: 'Ceylon Horizon is a peaceful private villa in Sri Lanka, created for slow living, warm hospitality, local food, and meaningful stays.',
  ogImageUrl: 'https://ceylonhorizon.com/og-image.jpg',
  heroTitle: 'Ceylon Horizon',
  heroTagline: 'A peaceful villa escape in Sri Lanka',
  heroDescription: 'Step away from the rush and settle into a gentler rhythm, with warm hospitality, generous Sri Lankan food, and space to truly unwind.',
  primaryCta: { label: 'Book Your Stay', link: '#contact' },
  secondaryCta: { label: 'Explore the Villa', link: '#about' },
  aboutTitle: 'Room to slow down',
  aboutBody: [
    'Ceylon Horizon is a private villa shaped around the simple pleasures of island life: unhurried breakfasts, long conversations, tropical air, and the feeling that everything has been thoughtfully taken care of.',
    'Designed for couples, families, remote workers, and curious travellers, it is a welcoming base for rest, connection, and discovering Sri Lanka at your own pace.',
  ],
  experienceSectionTitle: 'The art of an easy stay',
  experienceSectionDescription: 'Everything you need for days that feel full, without ever feeling busy.',
  experienceCards: [
    { icon: '01', title: 'Peaceful private stay', description: 'A calm, intimate setting with the freedom to make the villa entirely your own.' },
    { icon: '02', title: 'Sri Lankan food', description: 'Fresh local flavours, generous home-style cooking, and meals worth lingering over.' },
    { icon: '03', title: 'Outdoor living', description: 'Shaded terraces and tropical spaces made for reading, resting, and gathering.' },
    { icon: '04', title: 'Family comfort', description: 'Thoughtful, flexible spaces where every generation can settle in with ease.' },
    { icon: '05', title: 'Work from the villa', description: 'Reliable comfort and quiet corners for when a little focused time is needed.' },
    { icon: '06', title: 'Local discoveries', description: 'Beaches, food, culture, and nature, with local guidance when you want it.' },
  ],
  gallerySectionTitle: 'A glimpse of life here',
  gallerySectionDescription: 'Sun-warmed spaces, tropical textures, and room to breathe.',
  galleryImages: [
    { imageUrl: '/images/ceylon-horizon-hero.jpg', alt: 'Tropical villa and pool at golden hour', caption: 'The villa, held by the landscape' },
    { imageUrl: null, tone: 'terrace', alt: 'Shaded tropical terrace', caption: 'Quiet corners for slow afternoons' },
    { imageUrl: null, tone: 'table', alt: 'Sri Lankan table setting', caption: 'Fresh flavours, shared generously' },
    { imageUrl: null, tone: 'garden', alt: 'Lush tropical garden', caption: 'The easy rhythm of outdoor living' },
  ],
  locationTitle: 'Sri Lanka, at a gentler pace',
  locationBody: 'Ceylon Horizon places you close to the island experiences that stay with you, while giving you a private, peaceful place to return to. Exact location details and tailored directions are shared with confirmed guests.',
  locationPoints: ['Beaches', 'Local food', 'Culture', 'Nature', 'Slow travel'],
  contactTitle: 'Come stay awhile',
  contactBody: 'Tell us when you are thinking of visiting and who you are travelling with. We will be happy to help shape an easy, memorable stay.',
  whatsappLink: 'https://wa.me/',
  emailLink: 'mailto:hello@ceylonhorizon.com',
  emailAddress: 'hello@ceylonhorizon.com',
  phoneNumber: '+94 XX XXX XXXX',
  footerDescription: 'A peaceful private villa for slow, meaningful stays in Sri Lanka.',
}
