export const fallbackContent = {
  seoTitle: 'Ceylon Horizon | A Peaceful Villa Escape in Sri Lanka',
  seoDescription: 'Ceylon Horizon is a peaceful private villa in Sri Lanka, created for slow living, warm hospitality, local food, and meaningful stays.',
  ogImageUrl: 'https://ceylonhorizon.com/og-image.jpg',
  heroTitle: 'Ceylon Horizon',
  heroTagline: 'A peaceful villa escape in Sri Lanka',
  heroDescription: 'Step away from the rush and settle into a gentler rhythm, with warm hospitality, generous Sri Lankan food, and space to truly unwind.',
  primaryCta: { label: 'Book Your Stay', link: '#contact' },
  secondaryCta: { label: 'Explore the Villa', link: '#about' },
  aboutTitle: 'Room to slow down',
  aboutBody: [
    'Ceylon Horizon is a private villa shaped around the simple pleasures of island life: unhurried breakfasts, long conversations, tropical air, and the feeling that everything has been thoughtfully taken care of.',
    'Designed for couples, families, remote workers, and curious travellers, it is a welcoming base for rest, connection, and discovering Sri Lanka at your own pace.',
  ],
  experienceSectionTitle: 'The art of an easy stay',
  experienceSectionDescription: 'Everything you need for days that feel full, without ever feeling busy.',
  experienceCards: [
    { icon: '01', title: 'Peaceful private stay', description: 'A calm, intimate setting with the freedom to make the villa entirely your own.' },
    { icon: '02', title: 'Sri Lankan food', description: 'Fresh local flavours, generous home-style cooking, and meals worth lingering over.' },
    { icon: '03', title: 'Outdoor living', description: 'Shaded terraces and tropical spaces made for reading, resting, and gathering.' },
    { icon: '04', title: 'Family comfort', description: 'Thoughtful, flexible spaces where every generation can settle in with ease.' },
    { icon: '05', title: 'Work from the villa', description: 'Reliable comfort and quiet corners for when a little focused time is needed.' },
    { icon: '06', title: 'Local discoveries', description: 'Beaches, food, culture, and nature, with local guidance when you want it.' },
  ],
  gallerySectionTitle: 'A glimpse of life here',
  gallerySectionDescription: 'Concrete, timber, glass, and a garden that moves through the house.',
  galleryImages: [
    { imageUrl: '/images/ceylon-horizon-hero.jpg', alt: 'Tropical villa and pool at golden hour', caption: 'The villa, held by the landscape' },
    { imageUrl: '/images/gallery/villa-exterior-evening.jpg', alt: 'Ceylon Horizon exterior illuminated at blue hour', caption: 'A quiet arrival at blue hour' },
    { imageUrl: '/images/gallery/villa-lobby.jpg', alt: 'Double-height villa lounge with timber chairs and sculptural lights', caption: 'Warm light, generous space' },
    { imageUrl: '/images/gallery/terrace-dining.jpg', alt: 'Open-air dining terrace overlooking tropical greenery', caption: 'Dinner with the garden close by' },
    { imageUrl: '/images/gallery/atrium-lounge.jpg', alt: 'Leather chair beside a lush indoor garden and glass walls', caption: 'A room shaped around the garden' },
    { imageUrl: '/images/gallery/villa-courtyard.jpg', alt: 'Modern villa courtyard with dining area and glass bridge', caption: 'Architecture open to the sky' },
    { imageUrl: '/images/gallery/garden-entrance.jpg', alt: 'Illuminated villa entrance beside a dense tropical garden', caption: 'The garden at the doorstep' },
    { imageUrl: '/images/gallery/garden-lounge-dog.jpg', alt: 'Golden retriever in a glass-walled garden lounge', caption: 'Good company is always welcome' },
    { imageUrl: '/images/gallery/skylit-atrium.jpg', alt: 'Skylit atrium with a mature indoor tree and floating stair', caption: 'Daylight filters through every level' },
    { imageUrl: '/images/gallery/cantilever-villa.jpg', alt: 'Cantilevered concrete villa room above tropical planting', caption: 'Framed views into the canopy' },
    { imageUrl: '/images/gallery/stair-landing.jpg', alt: 'Timber stair landing with trailing plants and pendant lights', caption: 'Small details, softly considered' },
    { imageUrl: '/images/gallery/indoor-garden.jpg', alt: 'Multi-level indoor garden with stairs and leather reading chair', caption: 'Greenery at the heart of the house' },
    { imageUrl: '/images/gallery/garden-staircase-night.jpg', alt: 'Floating timber staircase above a garden at night', caption: 'The house after dusk' },
    { imageUrl: '/images/gallery/garden-staircase-dog.jpg', alt: 'Golden retriever at the top of a garden staircase', caption: 'A familiar face on the landing' },
    { imageUrl: '/images/gallery/dog-on-stairs.jpg', alt: 'Golden retriever walking down timber steps against a dark concrete wall', caption: 'Every corner has a little life' },
    { imageUrl: '/images/gallery/garden-stairs-dog.jpg', alt: 'Golden retriever descending open timber stairs through tropical planting', caption: 'Paths through the garden' },
    { imageUrl: '/images/gallery/tropical-corridor-dog.jpg', alt: 'Golden retriever beside a glass corridor and tropical foliage', caption: 'Inside and outside, gently blurred' },
  ],
  locationTitle: 'Sri Lanka, at a gentler pace',
  locationBody: 'Ceylon Horizon places you close to the island experiences that stay with you, while giving you a private, peaceful place to return to. Exact location details and tailored directions are shared with confirmed guests.',
  locationPoints: ['Beaches', 'Local food', 'Culture', 'Nature', 'Slow travel'],
  contactTitle: 'Come stay awhile',
  contactBody: 'Tell us when you are thinking of visiting and who you are travelling with. We will be happy to help shape an easy, memorable stay.',
  whatsappLink: 'https://wa.me/',
  emailLink: 'mailto:hello@ceylonhorizon.com',
  emailAddress: 'hello@ceylonhorizon.com',
  phoneNumber: '+94 XX XXX XXXX',
  footerDescription: 'A peaceful private villa for slow, meaningful stays in Sri Lanka.',
}
